name: gamevault_web
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  openapi_generator_annotations: ^6.1.0

  cupertino_icons: ^1.0.8
  gamevault_client_sdk:
    git: https://github.com/felixjulianheitmann/gamevault_client_sdk.git

  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_bloc: ^9.1.0
  flutter_secure_storage_linux: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: any
  openapi_generator: ^6.1.0
  http:
  build_runner: ^2.4.15
  
flutter:
  uses-material-design: true
  generate: true