name: publish-web
on: 
  workflow_dispatch: 
    inputs:
      tag:
        type: string  
        description: the tag used for this action
        required: true
      distance:
        type: string  
        description: number of additional builds since last tag
        required: true

permissions: 
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: print version
      run: |
        echo Version: ${{ inputs.tag }}
        echo Distance: ${{ inputs.distance }}
        
    - name: Download builds
      uses: "actions/download-artifact@v4"
      with:
        name: clavis-web-${{ inputs.tag }}-${{ github.sha }}
        path: ${{github.workspace}}/tmp.cicd/builds-web

    - name: list downloads
      run: ls ${{github.workspace}}/tmp.cicd/builds-web
        
    - name: build docker
      run: |
        docker build --build-arg BUILD_DIR=tmp.cicd/builds-web --tag clavis:${{ inputs.tag }} --tag clavis:latest .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: push docker
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ghcr.io/felixjulianheitmann
        image: clavis
        tags: ${{ inputs.tag }} latest
