name: publish-windows
description: publish the windows installer
inputs:
  tag:
    type: string
    description: the tag used for this action
    required: true
  distance:
    type: string
    description: number of additional builds since last tag
    required: true
  versionEncoded:
    type: string
    description: a version in form of "x.x.x.x"
    required: true
  token:
    type: string
    required: true


runs:
  using: "composite"
  steps:
  - name: print version
    shell: pwsh
    run: |
      echo Version: ${{ inputs.tag }}
      echo Distance: ${{ inputs.distance }}

  - uses: actions/checkout@v4
  - name: Download builds
    uses: "actions/download-artifact@v4"
    with:
      name: clavis-windows-amd64-${{ inputs.tag }}-${{ github.sha }}
      path: ${{github.workspace}}/tmp.cicd/builds-windows

  - name: list for debugging
    shell: pwsh
    run: |
      ls '${{github.workspace}}/tmp.cicd/builds-windows'
      ls '${{github.workspace}}'

  - name: bundle installer
    shell: pwsh
    run: ISCC.exe -DversionStrict="${{ inputs.versionEncoded }}" -Dversion="${{ inputs.tag }}-${{ inputs.distance }}" -DbuildDir='${{github.workspace}}/tmp.cicd/builds-windows' -Otarget '${{github.workspace}}\package\win-installer.iss'

  - name: Release
    uses: softprops/action-gh-release@v2
    with:
      files: target/*
      draft: ${{ inputs.distance != 0 }}
      make_latest: ${{ inputs.distance == 0 }}
      generate_release_notes: true
      fail_on_unmatched_files: true
      token: ${{ inputs.token }}