name: Flutter Build

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened

jobs:
  build-web:
    outputs:
      tag: ${{ steps.build.outputs.tag }}
      distance: ${{ steps.build.outputs.distance }}
      parsedVersion: ${{ steps.build.outputs.parsedVersion }}
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      with:
        platform: web
        arch: amd64
      id: build

  build-linux:
    outputs:
      tag: ${{ steps.build.outputs.tag }}
      distance: ${{ steps.build.outputs.distance }}
      parsedVersion: ${{ steps.build.outputs.parsedVersion }}
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      with:
        platform: linux
        arch: amd64
      id: build

  build-android:
    outputs:
      tag: ${{ steps.build.outputs.tag }}
      distance: ${{ steps.build.outputs.distance }}
      parsedVersion: ${{ steps.build.outputs.parsedVersion }}
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      with:
        platform: android
        arch: amd64
      id: build

  build-windows:
    outputs:
      tag: ${{ steps.build.outputs.tag }}
      distance: ${{ steps.build.outputs.distance }}
      parsedVersion: ${{ steps.build.outputs.parsedVersion }}
      
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      with:
        platform: windows
        arch: amd64
      id: build

  package-web:
    runs-on: ubuntu-latest
    needs: build-web
    permissions:
      packages: write

    if: ${{ needs.build-web.outputs.distance == 0 }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish-web
      with:
        tag: ${{ needs.build-web.outputs.tag }}
        distance: ${{ needs.build-web.outputs.distance }}
        token: ${{ secrets.GITHUB_TOKEN }}

  package-rpm:
    runs-on: ubuntu-latest
    needs: build-linux
    permissions:
      packages: write
      contents: write

    if: ${{ needs.build-linux.outputs.distance == 0 }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish-rpm
      with:
        tag: ${{ needs.build-linux.outputs.tag }}
        distance: ${{ needs.build-linux.outputs.distance }}
        token: ${{ secrets.GITHUB_TOKEN }}

  package-deb:
    runs-on: ubuntu-latest
    needs: build-linux
    permissions:
      packages: write
      contents: write

    # if: ${{ needs.build-linux.outputs.distance == 0 }} # activated for debugging
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish-deb
      with:
        tag: ${{ needs.build-linux.outputs.tag }}
        distance: ${{ needs.build-linux.outputs.distance }}
        token: ${{ secrets.GITHUB_TOKEN }}

  package-windows:
    runs-on: windows-latest
    needs: build-windows
    permissions:
      packages: write
      contents: write

    if: ${{ needs.build-windows.outputs.distance == 0 }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish-windows
      with:
        tag: ${{ needs.build-windows.outputs.tag }}
        distance: ${{ needs.build-windows.outputs.distance }}
        versionEncoded: ${{ fromJson(needs.build-windows.outputs.parsedVersion)['versionEncoded'] }}
        token: ${{ secrets.GITHUB_TOKEN }}
