name: Flutter Build

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened

permissions: 
  packages: write
  contents: write

jobs:
  build-web:
    uses: ./.github/workflows/build.yaml
    with:
      platform: web
      arch: amd64
      runner: ubuntu-latest

  build-linux:
    uses: ./.github/workflows/build.yaml
    with:
      platform: linux
      arch: amd64
      runner: ubuntu-latest

  build-android:
    uses: ./.github/workflows/build.yaml
    with:
      platform: apk
      arch: amd64
      runner: ubuntu-latest

  build-windows:
    uses: ./.github/workflows/build.yaml
    with:
      platform: windows
      arch: amd64
      runner: windows-latest

  package-web:
    if: ${{ needs.build-web.outputs.distance == 0 }}
    uses: ./.github/workflows/publish-web.yaml
    needs: build-web
    with:
      distance: ${{ needs.build-web.outputs.distance }}
      tag: ${{ needs.build-web.outputs.tag }}
      is-prerelease: ${{ needs.build-web.outputs.is-prerelease }}

  package-rpm:
    if: ${{ needs.build-linux.outputs.distance == 0 }}
    uses: ./.github/workflows/publish-rpm.yaml
    needs: build-linux
    with:
      distance: ${{ needs.build-linux.outputs.distance }}
      tag: ${{ needs.build-linux.outputs.tag }}
      is-prerelease: ${{ needs.build-web.outputs.is-prerelease }}

  package-deb:
    if: ${{ needs.build-linux.outputs.distance == 0 }}
    uses: ./.github/workflows/publish-deb.yaml
    needs: build-linux
    with:
      distance: ${{ needs.build-linux.outputs.distance }}
      arch: amd64
      tag: ${{ needs.build-linux.outputs.tag }}
      is-prerelease: ${{ needs.build-web.outputs.is-prerelease }}

  package-android:
    if: ${{ needs.build-android.outputs.distance == 0 }}
    uses: ./.github/workflows/publish-apk.yaml
    needs: build-android
    with:
      distance: ${{ needs.build-android.outputs.distance }}
      tag: ${{ needs.build-android.outputs.tag }}
      is-prerelease: ${{ needs.build-web.outputs.is-prerelease }}
    
  package-windows:
    if: ${{ needs.build-windows.outputs.distance == 0 }}
    uses: ./.github/workflows/publish-windows.yaml
    needs: build-windows
    with:
      distance: ${{ needs.build-windows.outputs.distance }}
      tag: ${{ needs.build-windows.outputs.tag }}
      versionEncoded: ${{ fromJson(needs.build-windows.outputs.parsedVersion)['versionEncoded'] }}
      is-prerelease: ${{ needs.build-web.outputs.is-prerelease }}
