name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [web, android, linux, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.7.2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter ${{ matrix.platform }} app
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            flutter build apk --release
          elif [ "${{ matrix.platform }}" == "web" ]; then
            flutter build web --release
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            flutter build linux --release
          elif [ "${{ matrix.platform }}" == "windows" ]; then
            flutter build windows --release
          fi

      - name: Upload build artifacts
        if: success() && (matrix.platform == 'android' || matrix.platform == 'web' || matrix.platform == 'linux' || matrix.platform == 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/${{ matrix.platform }}/*.apk
            build/${{ matrix.platform }}/*.exe
            build/${{ matrix.platform }}/*.dmg
            build/${{ matrix.platform }}/*.tar.xz
            build/${{ matrix.platform }}/*.zip