name: publish-rpm
on:
  workflow_call:
    inputs:
      tag:
        type: string  
        description: the tag used for this action
        required: true
      distance:
        type: string  
        description: number of additional builds since last tag
        required: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: print version
      shell: bash
      run: |
        echo Version: ${{ inputs.tag }}
        echo Distance: ${{ inputs.distance }}
        
    - uses: actions/checkout@v4
    - name: Download builds
      uses: "actions/download-artifact@v4"
      with:
        name: clavis-linux-amd64-${{ inputs.tag }}-${{ github.sha }}
        path: ${{github.workspace}}/tmp.cicd/build

    - name: list downloads
      shell: bash
      run: ls ${{github.workspace}}/tmp.cicd/build
        
    - name: build rpm
      shell: bash
      run: |
        ./package/rpm/bundle-rpm.sh tmp.cicd/build ${{ inputs.tag }} x86_64

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: package/rpm/rpmbuild/RPMS/x86_64/*
        draft: ${{ inputs.distance != 0 }}
        make_latest: ${{ inputs.distance == 0 }}
        generate_release_notes: true
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
