name: publish-apk
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: the tag used for this action
        required: true
      distance:
        type: string
        description: number of additional builds since last tag
        required: true
      is-prerelease:
        type: boolean
        description: whether this is a pre-release
        required: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: print version
      shell: bash
      run: |
        echo Version: ${{ inputs.tag }}
        echo Distance: ${{ inputs.distance }}

    - uses: actions/checkout@v4
    - name: Download builds
      uses: "actions/download-artifact@v4"
      with:
        name: clavis-apk-amd64-${{ inputs.tag }}-${{ github.sha }}
        path: ${{github.workspace}}/tmp.cicd/build

    - name: list downloads
      shell: bash
      run: ls ${{github.workspace}}/tmp.cicd/build

    - name: rename build file
      run: |
        mv ${{github.workspace}}/tmp.cicd/build/app/outputs/apk/release/app-release.apk ${{github.workspace}}/clavis_${{ inputs.tag }}.apk

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{github.workspace}}/clavis_${{ inputs.tag }}.apk
        draft: ${{ inputs.is-prerelease }}
        make_latest: ${{ !inputs.is-prerelease }}
        generate_release_notes: true
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
