name: publish-windows
on:
  workflow_call:
    inputs:
      tag:
        type: string  
        description: the tag used for this action
        required: true
      distance:
        type: string  
        description: number of additional builds since last tag
        required: true
      versionEncoded:
        type: string
        description: a version in form of "x.x.x.x"
        required: true

permissions:
  contents: write
        
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: print version
      shell: pwsh
      run: |
        echo Version: ${{ inputs.tag }}
        echo Distance: ${{ inputs.distance }}

    - uses: actions/checkout@v4
    - name: Download builds
      uses: "actions/download-artifact@v4"
      with:
        name: clavis-windows-amd64-${{ inputs.tag }}-${{ github.sha }}
        path: ${{github.workspace}}/tmp.cicd/build

    - name: list for debugging
      shell: pwsh
      run: |
        ls '${{github.workspace}}/tmp.cicd/build'
        ls '${{github.workspace}}'

    - name: bundle installer
      shell: pwsh
      run: ISCC.exe -DversionStrict="${{ inputs.versionEncoded }}" -Dversion="${{ inputs.tag }}" -DbuildDir='${{github.workspace}}/tmp.cicd/build' -Otarget '${{github.workspace}}\package\win-installer.iss'

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/*
        draft: ${{ inputs.distance != 0 }}
        make_latest: ${{ inputs.distance == 0 }}
        generate_release_notes: true
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
  